### ISSUE TITLE
Api Change & Reply System

### ISSUE THREAD

**Issue by MerBudd** [Lebyy/Discord-ChatBot#1]
Is there anyway you can change the API? I messed around with it a little but it just says undefined. Also can you make the bot actually reply instead of quoting? I don't know how to do it, maybe you can (i cant do pull requests i put it here hopefully you don't mind)

**Comment by Lebyy** [comment]
There are something called rate-limits in the api that is why you got the undefined error.
Yes I can remove the quoting system

**Comment by Lebyy** [comment]
You can even open a pr.

**Comment by MerBudd** [comment]
pr? idk what that means but uhh the quoting is fine, i just would've liked a "reply" system (you know, the one that says like replying to ___ and has a ping/no ping option) if you don't know how to do it, no problem. It's just that i've seen a few bots do it so it must be possible. This is still fine and you saved my day with your bot <3

**Comment by Lebyy** [comment]
> pr? idk what that means but uhh the quoting is fine, i just would've liked a "reply" system (you know, the one that says like replying to ___ and has a ping/no ping option) if you don't know how to do it, no problem. It's just that i've seen a few bots do it so it must be possible. This is still fine and you saved my day with your bot <3

I can do that also "pr" means pull request xD

**Comment by MerBudd** [comment]
> > pr? idk what that means but uhh the quoting is fine, i just would've liked a "reply" system (you know, the one that says like replying to ___ and has a ping/no ping option) if you don't know how to do it, no problem. It's just that i've seen a few bots do it so it must be possible. This is still fine and you saved my day with your bot <3
> 
> I can do that also "pr" means pull request xD

yeah i don't really know how to do pull requests lol... and also did you code the reply system?
