### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Hen105** [Lebyy/Discord-ChatBot#4]
When I try to run it this error message pops up in console
![EEBE24B0-49D0-4790-95B8-879CBBC06583](https://user-images.githubusercontent.com/74580305/151741134-c0ce183c-f3aa-449c-9012-ee811f73cee6.jpeg)

**Comment by Lebyy** [comment]
The code is in ES not ESM you have to change all `require` to `import` and do the necessary changes.

**Comment by Hen105** [comment]
How do I change that on replit

**Comment by Hen105** [comment]
I just changed the top text to import and now I am getting this error ![image](https://user-images.githubusercontent.com/74580305/151806929-25c31bcb-bea6-474a-bfb7-385e092533bf.jpeg)![image](https://user-images.githubusercontent.com/74580305/151806975-f39f2890-54b7-4114-bc15-7fcaa5a97003.jpeg)

**Comment by hz-gooi** [comment]
`const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));`

Try Changing it to the above code
