### ISSUE TITLE
Bot shuts down moment it tries to send back a reply

### ISSUE THREAD

**Issue by JustinSUF** [Lebyy/Discord-ChatBot#5]
Heyo, when the bot tries to respond back to a user, it proceeds to crash and give me this error

`Uncaught DiscordAPIError DiscordAPIError[50006]: Cannot send an empty message
    at runRequest (c:\Users\justi\Desktop\Discord-ChatBot-master\node_modules\@discordjs\rest\dist\index.js:667:15)
    at processTicksAndRejections (internal/process/task_queues:95:5)`

**Comment by lord0p2005** [comment]
By removing the `message.channel.sendTyping();` line, the bot should no longer attempt to send an empty message and should properly handle incoming messages in the "chatbot" channel.

`// ...

client.on("messageCreate", async (message) => {
  if (message.channel.name == "chatbot") {
    // The bot will only look for messages with the channel named "chatbot"
    if (message.author.bot) return;

    message.content = message.content
      .replace(/@(everyone)/gi, "everyone")
      .replace(/@(here)/gi, "here");

    if (message.content.includes(`@`)) {
      return message.reply({
        content: "**:x: Please don't mention anyone**",
        allowedMentions: { repliedUser: true },
      });
    }

    if (!message.content) {
      return message.reply({
        content: "Please say something.",
        allowedMentions: { repliedUser: true },
      });
    }

    const reply = await scb.chat(
      {
        message: message.content,
        name: client.user.username,
        master: "CoolOwnerName",
        user: message.author.id,
      },
      "en"
    );

    message.reply({
      content: reply,
      allowedMentions: { repliedUser: true },
    });
  }
});
`
